# Generated by Django 5.1.5 on 2025-01-23 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_models',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
