# Generated by Django 5.1.5 on 2025-01-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_models',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
