# Generated by Django 5.1.5 on 2025-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_alter_post_models_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_models',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
