# Generated by Django 5.1.5 on 2025-01-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0006_alter_post_models_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_models',
            options={'ordering': ['-created']},
        ),
    ]
