# Generated by Django 5.1.5 on 2025-01-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0008_tags_post_models_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tags',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
