# Generated by Django 5.1.5 on 2025-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_alter_tags_options_tags_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
