# Generated by Django 5.1.5 on 2025-02-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0010_tags_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
